<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Pipboy.Avalonia</RootNamespace>
    <AssemblyName>Pipboy.Avalonia</AssemblyName>
	<PackageId>Pipboy.Avalonia</PackageId>
	<PackageIcon>pip-terminal.png</PackageIcon>
    <Version>1.1.5-beta</Version>
    <Authors>Dong</Authors>
    <Description>A Fallout 4 Pip-Boy inspired theme library for Avalonia UI.</Description>
    <PackageTags>avalonia;theme;fallout;pipboy;retro;ui;dark-theme</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/NeverMorewd/Pipboy.Avalonia</RepositoryUrl>
    <PackageProjectUrl>https://github.com/NeverMorewd/Pipboy.Avalonia</PackageProjectUrl>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\..\pip-terminal.png" Pack="true" PackagePath="\" Link="Properties\pip-terminal.png"/>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="True" PackagePath="\" />
  </ItemGroup>

</Project>
    